# Generated by Django 3.1.5 on 2021-01-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_text', models.CharField(max_length=500)),
                ('item_prio', models.IntegerField(default=0)),
                ('item_done', models.BooleanField(default=False)),
            ],
        ),
    ]
