# Generated by Django 3.1.5 on 2021-01-04 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_app', '0002_listuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListUser',
        ),
    ]
